# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Ratis git ref (branch, tag or commit hash)
        default: ''
        required: false

jobs:
  build:
    uses: ./.github/workflows/check.yaml
    with:
      script: build
      script-args: -Prelease
      timeout-minutes: 30
    secrets: inherit

  compile:
    needs:
      - build
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
      fail-fast: false
    uses: ./.github/workflows/check.yaml
    with:
      java-version: ${{ matrix.java }}
      needs-source-tarball: true
      script: compile
      script-args: -Djavac.version=${{ matrix.java }}
      split: ${{ matrix.java }}
      timeout-minutes: 30
    secrets: inherit

  release:
    uses: ./.github/workflows/check.yaml
    with:
      script: release
      timeout-minutes: 30
    secrets: inherit

  repro:
    needs:
      - build
    uses: ./.github/workflows/check.yaml
    with:
      needs-maven-repo: true
      script: repro
      script-args: -Prelease
      timeout-minutes: 30
    secrets: inherit

  basic:
    strategy:
      matrix:
        check:
          - author
          - checkstyle
          - findbugs
          - rat
      fail-fast: false
    uses: ./.github/workflows/check.yaml
    with:
      script: ${{ matrix.check }}
      timeout-minutes: 30
    secrets: inherit

  unit:
    strategy:
      matrix:
        profile:
          - grpc
          - server
          - misc
          - flaky
      fail-fast: false
    uses: ./.github/workflows/check.yaml
    with:
      script: unit
      script-args: -P${{ matrix.profile }}-tests
      split: ${{ matrix.profile }}
      timeout-minutes: 60
    secrets: inherit

  coverage:
    needs:
      - build
      - unit
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    if: (github.repository == 'apache/ratis' || github.repository == 'apache/incubator-ratis') && github.event_name != 'pull_request'
    steps:
        - name: Checkout project
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Cache for maven dependencies
          uses: actions/cache/restore@v4
          with:
            path: |
              ~/.m2/repository
              !~/.m2/repository/org/apache/ratis
            key: maven-repo-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-repo-
        - name: Setup java 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: target/artifacts
        - name: Untar binaries
          run: |
            mkdir -p ratis-assembly/target
            tar xzvf target/artifacts/ratis-bin/ratis-assembly-*.tar.gz -C ratis-assembly/target
        - name: Calculate combined coverage
          run: ./dev-support/checks/coverage.sh
        - name: Upload coverage to Sonar
          run: ./dev-support/checks/sonar.sh
          env:
            SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Archive build results
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: ${{ github.job }}
            path: target/${{ github.job }}
